"""Email report — sends periodic scan summaries via SMTP."""

from __future__ import annotations

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from agents import function_tool

logger = logging.getLogger(__name__)


def _get_smtp_config() -> dict | None:
    """Read SMTP config from env. Returns None if any required var is missing."""
    host = os.environ.get("OPENCMO_SMTP_HOST")
    port = os.environ.get("OPENCMO_SMTP_PORT")
    user = os.environ.get("OPENCMO_SMTP_USER")
    password = os.environ.get("OPENCMO_SMTP_PASS")
    recipient = os.environ.get("OPENCMO_REPORT_EMAIL")

    if not all([host, port, user, password, recipient]):
        return None

    return {
        "host": host,
        "port": int(port),
        "user": user,
        "password": password,
        "recipient": recipient,
    }


def _build_report_html(
    project: dict,
    latest_scans: dict,
    previous_scans: dict | None,
    discussions: list[dict],
    serp_latest: list[dict],
) -> str:
    """Build HTML email body from scan data."""
    brand = project["brand_name"]
    url = project["url"]

    sections = []
    sections.append(f"<h1>OpenCMO Daily Report: {brand}</h1>")
    sections.append(f"<p><a href='{url}'>{url}</a></p>")
    sections.append("<hr>")

    # SEO section
    seo = latest_scans.get("seo")
    if seo:
        score = seo.get("score")
        score_str = f"{score:.0%}" if score is not None else "N/A"
        delta_str = ""
        if previous_scans and previous_scans.get("seo"):
            prev_score = previous_scans["seo"].get("score")
            if score is not None and prev_score is not None:
                delta = (score - prev_score) * 100
                if delta > 0:
                    delta_str = f' <span style="color:green">(+{delta:.1f}%)</span>'
                elif delta < 0:
                    delta_str = f' <span style="color:red">({delta:.1f}%)</span>'
        sections.append(f"<h2>SEO Performance</h2>")
        sections.append(f"<p>Score: <strong>{score_str}</strong>{delta_str}</p>")
        sections.append(f"<p>Last scan: {seo['scanned_at'][:16]}</p>")
    else:
        sections.append("<h2>SEO Performance</h2><p>No data yet</p>")

    # GEO section
    geo = latest_scans.get("geo")
    if geo:
        geo_score = geo.get("score", 0)
        delta_str = ""
        if previous_scans and previous_scans.get("geo"):
            prev_score = previous_scans["geo"].get("score")
            if prev_score is not None:
                delta = geo_score - prev_score
                if delta > 0:
                    delta_str = f' <span style="color:green">(+{delta})</span>'
                elif delta < 0:
                    delta_str = f' <span style="color:red">({delta})</span>'
        sections.append(f"<h2>GEO Score</h2>")
        sections.append(f"<p>Score: <strong>{geo_score}/100</strong>{delta_str}</p>")
        sections.append(f"<p>Last scan: {geo['scanned_at'][:16]}</p>")
    else:
        sections.append("<h2>GEO Score</h2><p>No data yet</p>")

    # Community section
    comm = latest_scans.get("community")
    if comm:
        sections.append(f"<h2>Community</h2>")
        sections.append(f"<p>{comm['total_hits']} discussion hits</p>")
    if discussions:
        sections.append("<h3>Top Discussions</h3><ul>")
        for d in discussions[:5]:
            sections.append(
                f"<li><a href='{d['url']}'>{d['title'][:80]}</a> "
                f"({d['platform']}, score: {d.get('raw_score', '—')})</li>"
            )
        sections.append("</ul>")

    # SERP section (optional)
    if serp_latest:
        sections.append("<h2>SERP Rankings</h2>")
        sections.append(
            "<table border='1' cellpadding='4' style='border-collapse:collapse'>"
            "<tr><th>Keyword</th><th>Position</th><th>URL</th><th>Checked</th></tr>"
        )
        for s in serp_latest:
            if s.get("error"):
                pos_str = "error"
            elif s.get("position") is None:
                pos_str = "not ranked"
            else:
                pos_str = f"#{s['position']}"
            url_found = s.get("url_found") or "—"
            sections.append(
                f"<tr><td>{s['keyword']}</td><td>{pos_str}</td>"
                f"<td>{url_found[:60]}</td><td>{s['checked_at'][:16]}</td></tr>"
            )
        sections.append("</table>")

    sections.append("<hr>")
    sections.append("<p><em>Generated by OpenCMO</em></p>")

    return "\n".join(sections)


async def send_report_impl(project_id: int) -> dict:
    """Build and send email report for a project."""
    from opencmo import storage

    config = _get_smtp_config()
    if not config:
        return {"ok": False, "error": "SMTP not configured"}

    project = await storage.get_project(project_id)
    if not project:
        return {"ok": False, "error": f"Project {project_id} not found"}

    latest = await storage.get_latest_scans(project_id)
    previous = await storage.get_previous_scans(project_id)
    discussions = await storage.get_tracked_discussions(project_id)
    serp_latest = await storage.get_all_serp_latest(project_id)

    html = _build_report_html(project, latest, previous, discussions, serp_latest)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"OpenCMO Report: {project['brand_name']}"
    msg["From"] = config["user"]
    msg["To"] = config["recipient"]
    msg.attach(MIMEText(html, "html"))

    try:
        port = config["port"]
        if port == 465:
            with smtplib.SMTP_SSL(config["host"], port, timeout=30) as server:
                server.login(config["user"], config["password"])
                server.send_message(msg)
        else:
            with smtplib.SMTP(config["host"], port, timeout=30) as server:
                server.starttls()
                server.login(config["user"], config["password"])
                server.send_message(msg)
        return {"ok": True, "recipient": config["recipient"]}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


@function_tool
async def send_email_report(project_id: int) -> str:
    """Send an email report with latest scan data for a project.

    Args:
        project_id: The project ID to generate a report for.
    """
    result = await send_report_impl(project_id)
    if result["ok"]:
        return f"Report sent to {result['recipient']}"
    else:
        return f"Failed to send report: {result['error']}"
