import html2pdf from "html2pdf.js";

const LOGO_URL = "/logo.png";

/**
 * Convert a logo image URL to a base64 data-URI so it can be
 * embedded reliably in the off-screen PDF container.
 */
async function loadLogoAsDataURI(): Promise<string> {
  try {
    const resp = await fetch(LOGO_URL);
    const blob = await resp.blob();
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return "";
  }
}

/**
 * Capture a specific DOM element and download it as a beautifully
 * formatted A4 PDF with the OpenCMO logo in the header and a
 * branded footer on every page.
 */
export async function downloadAsPDF({
  elementId,
  filename = "report.pdf",
  title = "AI CMO Report",
  subtitle,
}: {
  elementId: string;
  filename?: string;
  title?: string;
  subtitle?: string;
}) {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`[pdf] Element #${elementId} not found.`);
    return;
  }

  const logoDataURI = await loadLogoAsDataURI();

  // ---- build the off-screen container ----
  const container = document.createElement("div");
  Object.assign(container.style, {
    position: "absolute",
    left: "-9999px",
    top: "-9999px",
    width: "800px",
    padding: "40px 36px 30px",
    fontFamily: "'Helvetica Neue', Helvetica, Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    color: "#0f172a",
    lineHeight: "1.75",
    fontSize: "14px",
    background: "#ffffff",
  });

  // ---- header with logo ----
  const header = document.createElement("div");
  Object.assign(header.style, {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    borderBottom: "2px solid #e2e8f0",
    paddingBottom: "18px",
    marginBottom: "32px",
  });

  if (logoDataURI) {
    const logo = document.createElement("img");
    logo.src = logoDataURI;
    Object.assign(logo.style, {
      width: "44px",
      height: "44px",
      borderRadius: "10px",
      objectFit: "contain",
    });
    header.appendChild(logo);
  }

  const headerText = document.createElement("div");
  headerText.innerHTML = [
    `<div style="font-size:22px;font-weight:700;color:#020617;letter-spacing:-0.3px">${title}</div>`,
    subtitle
      ? `<div style="margin-top:2px;font-size:12px;color:#64748b">${subtitle}</div>`
      : "",
    `<div style="margin-top:2px;font-size:11px;color:#94a3b8">Generated by OpenCMO · ${new Date().toLocaleDateString("zh-CN")}</div>`,
  ].join("\n");
  header.appendChild(headerText);
  container.appendChild(header);

  // ---- body content ----
  const body = document.createElement("div");
  body.className = "prose prose-slate max-w-none";
  body.innerHTML = element.innerHTML;
  container.appendChild(body);

  // ---- footer ----
  const footer = document.createElement("div");
  Object.assign(footer.style, {
    borderTop: "1px solid #e2e8f0",
    marginTop: "40px",
    paddingTop: "14px",
    display: "flex",
    justifyContent: "space-between",
    fontSize: "10px",
    color: "#94a3b8",
  });
  footer.innerHTML = `
    <span>OpenCMO — AI-Powered Marketing Intelligence</span>
    <span>${new Date().toISOString().slice(0, 10)}</span>
  `;
  container.appendChild(footer);

  document.body.appendChild(container);

  // ---- generate PDF ----
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const opt: any = {
    margin: 12,
    filename,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, logging: false },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    pagebreak: { mode: ["avoid-all", "css", "legacy"] },
  };

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (html2pdf() as any).set(opt).from(container).save();
  } finally {
    document.body.removeChild(container);
  }
}
